name: splash_page
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.2.0
  lottie: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/others/
    - assets/fonts/

  fonts:
    - family: Cyberspace
      fonts:
        - asset: assets/fonts/Cyberspace.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic

    - family: ColumbiaSerial Bold
      fonts:
        - asset: assets/fonts/ColumbiaSerial.ttf

    - family: Hamlet
      fonts:
        - asset: assets/fonts/Hamlet.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
